In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("cleaned.csv")

In [3]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [29]:
df.tail()

,movie_id,title,tags
4801,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4802,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4803,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4804,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4805,25975,My Date with Drew,ever since the second grade when he first saw ...

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv = CountVectorizer(max_features=5000, stop_words="english")

In [7]:
vectors = cv.fit_transform(df.tags).toarray()

In [8]:
vectors.shape

(4806, 5000)

In [10]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [12]:
cv.vocabulary_

{'century': np.int64(737),
 'marine': np.int64(2773),
 'dispatched': np.int64(1277),
 'moon': np.int64(2988),
 'unique': np.int64(4697),
 'mission': np.int64(2954),
 'torn': np.int64(4551),
 'following': np.int64(1726),
 'orders': np.int64(3195),
 'protecting': np.int64(3516),
 'alien': np.int64(161),
 'civilization': np.int64(835),
 'action': np.int64(79),
 'adventure': np.int64(111),
 'fantasy': np.int64(1614),
 'sciencefiction': np.int64(3918),
 'cultureclash': np.int64(1069),
 'future': np.int64(1798),
 'society': np.int64(4142),
 'spacetravel': np.int64(4180),
 'futuristic': np.int64(1799),
 'romance': np.int64(3799),
 'space': np.int64(4174),
 'tribe': np.int64(4612),
 'soldier': np.int64(4147),
 'battle': np.int64(418),
 '3d': np.int64(42),
 'zoesaldana': np.int64(4993),
 'sigourneyweaver': np.int64(4075),
 'captain': np.int64(669),
 'long': np.int64(2668),
 'believed': np.int64(447),
 'dead': np.int64(1138),
 'come': np.int64(909),
 'life': np.int64(2626),
 'headed': np.int64(1998),
 'edge': np.int64(1394),
 'earth': np.int64(1383),
 'turner': np.int64(4639),
 'elizabeth': np.int64(1417),
 'quite': np.int64(3563),
 'ocean': np.int64(3159),
 'drugabuse': np.int64(1346),
 'exoticisland': np.int64(1546),
 'loveofone': np.int64(2703),
 'slife': np.int64(4125),
 'traitor': np.int64(4586),
 'shipwreck': np.int64(4047),
 'ship': np.int64(4046),
 'alliance': np.int64(168),
 'afterlife': np.int64(124),
 'fighter': np.int64(1669),
 'pirate': np.int64(3358),
 'aftercreditsstinger': np.int64(123),
 'johnnydepp': np.int64(2396),
 'orlandobloom': np.int64(3203),
 'keiraknightley': np.int64(2471),
 'message': np.int64(2878),
 'bond': np.int64(531),
 'past': np.int64(3276),
 'sends': np.int64(3983),
 'trail': np.int64(4581),
 'uncover': np.int64(4672),
 'sinister': np.int64(4095),
 'organization': np.int64(3198),
 'battles': np.int64(420),
 'political': np.int64(3403),
 'forces': np.int64(1737),
 'secret': np.int64(3949),
 'service': np.int64(4004),
 'alive': np.int64(166),
 'deceit': np.int64(1157),
 'reveal': np.int64(3725),
 'terrible': np.int64(4461),
 'truth': np.int64(4629),
 'crime': np.int64(1043),
 'spy': np.int64(4212),
 'basedonnovel': np.int64(407),
 'secretagent': np.int64(3950),
 'sequel': np.int64(3994),
 'britishsecretservice': np.int64(584),
 'danielcraig': np.int64(1102),
 'christophwaltz': np.int64(818),
 'death': np.int64(1147),
 'district': np.int64(1279),
 'attorney': np.int64(345),
 'harvey': np.int64(1982),
 'batman': np.int64(417),
 'assumes': np.int64(326),
 'responsibility': np.int64(3704),
 'crimes': np.int64(1045),
 'protect': np.int64(3515),
 'late': np.int64(2565),
 'reputation': np.int64(3689),
 'hunted': np.int64(2146),
 'gotham': np.int64(1886),
 'city': np.int64(833),
 'police': np.int64(3397),
 'department': np.int64(1188),
 'years': np.int64(4975),
 'later': np.int64(2566),
 'encounters': np.int64(1455),
 'mysterious': np.int64(3046),
 'kyle': np.int64(2538),
 'villainous': np.int64(4785),
 'new': np.int64(3103),
 'terrorist': np.int64(4468),
 'leader': np.int64(2583),
 'dark': np.int64(1112),
 'knight': np.int64(2519),
 'enemy': np.int64(1463),
 'drama': np.int64(1325),
 'thriller': np.int64(4511),
 'dccomics': np.int64(1136),
 'crimefighter': np.int64(1044),
 'secretidentity': np.int64(3952),
 'burglar': np.int64(621),
 'gothamcity': np.int64(1887),
 'vigilante': np.int64(4782),
 'cover': np.int64(1024),
 'superhero': np.int64(4348),
 'terrorism': np.int64(4467),
 'destruction': np.int64(1211),
 'imax': np.int64(2181),
 'flood': np.int64(1715),
 'christianbale': np.int64(805),
 'michaelcaine': np.int64(2893),
 'garyoldman': np.int64(1817),
 'christophernolan': np.int64(815),
 'john': np.int64(2386),
 'carter': np.int64(699),
 'war': np.int64(4833),
 'military': np.int64(2920),
 'transported': np.int64(4593),
 'exotic': np.int64(1545),
 'planet': np.int64(3369),
 'mars': np.int64(2791),
 'reluctantly': np.int64(3669),
 'embroiled': np.int64(1432),
 'epic': np.int64(1489),
 'conflict': np.int64(951),
 'world': np.int64(4948),
 'brink': np.int64(581),
 'collapse': np.int64(889),
 'humanity': np.int64(2137),
 'realizes': np.int64(3613),
 'survival': np.int64(4376),
 'people': np.int64(3304),
 'hands': np.int64(1956),
 'medallion': np.int64(2843),
 'princess': np.int64(3476),
 'steampunk': np.int64(4244),
 'escape': np.int64(1499),
 'superhumanstrength': np.int64(4351),
 '19thcentury': np.int64(32),
 'samanthamorton': np.int64(3869),
 'seemingly': np.int64(3971),
 'spider': np.int64(4199),
 'man': np.int64(2753),
 'goes': np.int64(1872),
 'villain': np.int64(4784),
 'including': np.int64(2199),
 'shape': np.int64(4030),
 'superpowers': np.int64(4356),
 'alter': np.int64(176),
 'ego': np.int64(1404),
 'peter': np.int64(3322),
 'parker': np.int64(3257),
 'deals': np.int64(1145),
 'nemesis': np.int64(3093),
 'eddie': np.int64(1391),
 'gets': np.int64(1846),
 'caught': np.int64(719),
 'love': np.int64(2699),
 'triangle': np.int64(4611),
 'dualidentity': np.int64(1357),
 'amnesia': np.int64(197),
 'forgiveness': np.int64(1745),
 'wretch': np.int64(4960),
 'deathofafriend': np.int64(1148),
 'hostility': np.int64(2120),
 'marvelcomic': np.int64(2803),
 'revenge': np.int64(3730),
 'tobeymaguire': np.int64(4534),
 'kirstendunst': np.int64(2513),
 'jamesfranco': np.int64(2310),
 'samraimi': np.int64(3871),
 'kingdom': np.int64(2510),
 'wanted': np.int64(4830),
 'charming': np.int64(767),
 'taken': np.int64(4403),
 'hostage': np.int64(2118),
 'beautiful': np.int64(430),
 'bound': np.int64(544),
 'teen': np.int64(4437),
 '70': np.int64(48),
 'feet': np.int64(1648),
 'magical': np.int64(2737),
 'golden': np.int64(1875),
 'hair': np.int64(1948),
 'curious': np.int64(1074),
 'looking': np.int64(2672),
 'ticket': np.int64(4519),
 'locked': np.int64(2659),
 'away': np.int64(369),
 'strikes': np.int64(4294),
 'deal': np.int64(1141),
 'handsome': np.int64(1957),
 'thief': np.int64(4488),
 'unlikely': np.int64(4709),
 'duo': np.int64(1363),
 'sets': np.int64(4010),
 'packed': np.int64(3231),
 'escapade': np.int64(1498),
 'complete': np.int64(936),
 'super': np.int64(4346),
 'cop': np.int64(994),
 'horse': np.int64(2115),
 'gang': np.int64(1808),
 'thugs': np.int64(4517),
 'animation': np.int64(228),
 'family': np.int64(1604),
 'magic': np.int64(2736),
 'fairytale': np.int64(1591),
 'musical': np.int64(3036),
 'duringcreditsstinger': np.int64(1364),
 'mandymoore': np.int64(2756),
 'tony': np.int64(4547),
 'stark': np.int64(4230),
 'tries': np.int64(4614),
 'program': np.int64(3496),
 'things': np.int64(4491),
 'awry': np.int64(370),
 'heroes': np.int64(2034),
 'ultimate': np.int64(4663),
 'test': np.int64(4475),
 'fate': np.int64(1627),
 'hangs': np.int64(1961),
 'balance': np.int64(382),
 'emerges': np.int64(1435),
 'stop': np.int64(4273),
 'plans': np.int64(3373),
 'soon': np.int64(4159),
 'unexpected': np.int64(4687),
 'way': np.int64(4854),
 'global': np.int64(1866),
 'basedoncomicbook': np.int64(405),
 'vision': np.int64(4799),
 'marvelcinematicuniverse': np.int64(2802),
 'robertdowneyjr': np.int64(3775),
 'chrishemsworth': np.int64(800),
 'markruffalo': np.int64(2779),
 'harry': np.int64(1978),
 'begins': np.int64(442),
 'year': np.int64(4974),
 'discovers': np.int64(1267),
 'old': np.int64(3173),
 'book': np.int64(534),
 'marked': np.int64(2777),
 'property': np.int64(3509),
 'half': np.int64(1949),
 'blood': np.int64(510),
 'prince': np.int64(3475),
 'learn': np.int64(2588),
 'lord': np.int64(2676),
 'witch': np.int64(4917),
 'wizardry': np.int64(4924),
 'teenagecrush': np.int64(4439),
 'werewolf': np.int64(4870),
 'danielradcliffe': np.int64(1104),
 'rupertgrint': np.int64(3836),
 'emmawatson': np.int64(1444),
 'actions': np.int64(81),
 'god': np.int64(1870),
 'like': np.int64(2634),
 'hero': np.int64(2033),
 'left': np.int64(2596),
 'formidable': np.int64(1747),
 'takes': np.int64(4404),
 'modern': np.int64(2972),
 'day': np.int64(1133),
 'sort': np.int64(4164),
 'really': np.int64(3615),
 'needs': np.int64(3086),
 'superman': np.int64(4352),
 'threat': np.int64(4504),
 'quickly': np.int64(3560),
 'putting': np.int64(3550),
 'mankind': np.int64(2761),
 'greater': np.int64(1901),
 'danger': np.int64(1098),
 'known': np.int64(2523),
 'benaffleck': np.int64(452),
 'returns': np.int64(3720),
 'discover': np.int64(1264),
 'walk': np.int64(4819),
 'free': np.int64(1775),
 'abandoned': np.int64(52),
 'moved': np.int64(3012),
 'plots': np.int64(3387),
 'millions': np.int64(2925),
 'killed': np.int64(2500),
 'change': np.int64(748),
 'face': np.int64(1578),
 'forever': np.int64(1743),
 'steel': np.int64(4245),
 'savingtheworld': np.int64(3896),
 'kevinspacey': np.int64(2485),
 'katebosworth': np.int64(2455),
 'bryansinger': np.int64(604),
 'continues': np.int64(976),
 'adventures': np.int64(112),
 'james': np.int64(2308),
 'casino': np.int64(705),
 'betrayed': np.int64(468),
 'woman': np.int64(4926),
 'loved': np.int64(2701),
 '007': np.int64(1),
 'fights': np.int64(1672),
 'make': np.int64(2744),
 'latest': np.int64(2567),
 'personal': np.int64(3317),
 'pursuing': np.int64(3544),
 'determination': np.int64(1215),
 'mr': np.int64(3019),
 'white': np.int64(4880),
 'reveals': np.int64(3728),
 'far': np.int64(1616),
 'complex': np.int64(938),
 'dangerous': np.int64(1099),
 'imagined': np.int64(2180),
 'killing': np.int64(2504),
 'undercover': np.int64(4677),
 'marcforster': np.int64(2766),
 'jack': np.int64(2298),
 'works': np.int64(4947),
 'debt': np.int64(1151),
 'jones': np.int64(2409),
 'attempts': np.int64(338),
 'avoid': np.int64(365),
 'eternal': np.int64(1509),
 'fortuneteller': np.int64(1752),
 'monster': np.int64(2982),
 'daughter': np.int64(1121),
 'texas': np.int64(4478),
 'rangers': np.int64(3591),
 'chase': np.int64(768),
 'led': np.int64(2594),
 'survivor': np.int64(4381),
 'american': np.int64(191),
 'indian': np.int64(2206),
 'named': np.int64(3054),
 'health': np.int64(2003),
 'ranger': np.int64(3590),
 'mask': np.int64(2805),
 'riding': np.int64(3745),
 'silver': np.int64(4079),
 'teams': np.int64(4431),
 'bring': np.int64(578),
 'justice': np.int64(2445),
 'western': np.int64(4876),
 'partner': np.int64(3262),
 'outlaw': np.int64(3215),
 'lawyer': np.int64(2579),
 'train': np.int64(4582),
 'young': np.int64(4978),
 'boy': np.int64(551),
 'learns': np.int64(2590),
 'extraordinary': np.int64(1570),
 'powers': np.int64(3440),
 'journeys': np.int64(2423),
 'came': np.int64(646),
 'sent': np.int64(3988),
 'emerge': np.int64(1433),
 'save': np.int64(3892),
 'hope': np.int64(2104),
 'superhuman': np.int64(4350),
 'alieninvasion': np.int64(162),
 'reboot': np.int64(3626),
 'amyadams': np.int64(202),
 'michaelshannon': np.int64(2899),
 'incredible': np.int64(2201),
 'lion': np.int64(2644),
 'lucy': np.int64(2717),
 'susan': np.int64(4383),
 'return': np.int64(3717),
 'aid': np.int64(139),
 'threatened': np.int64(4506),
 'evil': np.int64(1527),
 'king': np.int64(2509),
 'help': np.int64(2027),
 'colorful': np.int64(904),
 'cast': np.int64(706),
 'characters': np.int64(757),
 'clan': np.int64(841),
 'embarks': np.int64(1430),
 'quest': np.int64(3556),
 'returned': np.int64(3718),
 'heir': np.int64(2017),
 'fictionalplace': np.int64(1663),
 'brothersisterrelationship': np.int64(596),
 'faith': np.int64(1592),
 'uncle': np.int64(4670),
 'fantasyworld': np.int64(1615),
 'threatens': np.int64(4508),
 'safety': np.int64(3858),
 'security': np.int64(3963),
 'nick': np.int64(3119),
 'director': np.int64(1254),
 'international': np.int64(2255),
 'agency': np.int64(129),
 'finds': np.int64(1691),
 'need': np.int64(3084),
 'team': np.int64(4430),
 'pull': np.int64(3532),
 'disaster': np.int64(1262),
 'spanning': np.int64(4183),
 'globe': np.int64(1867),
 'daring': np.int64(1111),
 'effort': np.int64(1401),
 'newyork': np.int64(3115),
 'chrisevans': np.int64(799),
 'crosses': np.int64(1055),
 'paths': np.int64(3279),
 'sure': np.int64(4364),
 'ruthless': np.int64(3846),
 'artist': np.int64(301),
 'using': np.int64(4737),
 'youth': np.int64(4983),
 'aboard': np.int64(58),
 'queen': np.int64(3552),
 'anne': np.int64(231),
 'doesn': np.int64(1296),
 'know': np.int64(2520),
 'fear': np.int64(1635),
 'sea': np.int64(3932),
 'mutiny': np.int64(3044),
 'sword': np.int64(4395),
 'sailing': np.int64(3861),
 'duke': np.int64(1361),
 'mermaid': np.int64(2876),
 'penélopecruz': np.int64(3303),
 'agents': np.int64(132),
 'smith': np.int64(4131),
 'tommy': np.int64(4543),
 'lee': np.int64(2595),
 'time': np.int64(4525),
 'seen': np.int64(3972),
 '15': np.int64(8),
 'men': np.int64(2864),
 'black': np.int64(499),
 'aliens': np.int64(164),
 'stake': np.int64(4219),
 'agent': np.int64(131),
 'travel': np.int64(4600),
 'right': np.int64(3748),
 'secrets': np.int64(3958),
 'universe': np.int64(4701),
 'told': np.int64(4538),
 'josh': np.int64(2416),
 'humankind': np.int64(2138),
 'comedy': np.int64(913),
 'timetravel': np.int64(4528),
 'willsmith': np.int64(4901),
 'tommyleejones': np.int64(4544),
 'joshbrolin': np.int64(2417),
 'immediately': np.int64(2182),
 'events': np.int64(1522),
 'dwarves': np.int64(1368),
 'try': np.int64(4631),
 'defend': np.int64(1170),
 'mountain': np.int64(3009),
 'treasure': np.int64(4604),
 'claim': np.int64(837),
 'elves': np.int64(1426),
 'army': np.int64(283),
 'orcs': np.int64(3192),
 'rise': np.int64(3755),
 'unite': np.int64(4699),
 'middle': np.int64(2906),
 'falls': np.int64(1598),
 'corruption': np.int64(1004),
 'hobbit': np.int64(2073),
 'dragon': np.int64(1324),
 'unlikelyfriendship': np.int64(4710),
 'swordandsorcery': np.int64(4396),
 'ianmckellen': np.int64(2156),
 'peterjackson': np.int64(3325),
 'outcast': np.int64(3213),
 'high': np.int64(2042),
 'parents': np.int64(3253),
 'leaving': np.int64(2593),
 'raised': np.int64(3584),
 'ben': np.int64(451),
 'aunt': np.int64(353),
 'teenagers': np.int64(4442),
 'trying': np.int64(4632),
 'figure': np.int64(1673),
 'got': np.int64(1885),
 'person': np.int64(3316),
 'today': np.int64(4535),
 'father': np.int64(1629),
 'understand': np.int64(4682),
 'disappearance': np.int64(1259),
 'leading': np.int64(2585),
 'lab': np.int64(2540),
 'dr': np.int64(1321),
 'set': np.int64(4006),
 'collision': np.int64(898),
 'course': np.int64(1018),
 'choices': np.int64(793),
 'use': np.int64(4734),
 'destiny': np.int64(1207),
 'lossoffather': np.int64(2687),
 'emmastone': np.int64(1442),
 'robin': np.int64(3781),
 'happens': np.int64(1966),
 'dying': np.int64(1370),
 'robert': np.int64(3773),
 'promises': np.int64(3502),
 'identity': np.int64(2164),
 'widow': np.int64(4885),
 'draws': np.int64(1330),
 'town': np.int64(4565),
 'sheriff': np.int64(4044),
 'middleages': np.int64(2907),
 'medieval': np.int64(2848),
 'russellcrowe': np.int64(3841),
 'cateblanchett': np.int64(713),
 'ridleyscott': np.int64(3746),
 'successfully': np.int64(4329),
 'escaped': np.int64(1500),
 'mountains': np.int64(3010),
 'ring': np.int64(3752),
 'continue': np.int64(975),
 'journey': np.int64(2422),
 'gold': np.int64(1874),
 'wizard': np.int64(4923),
 'shocking': np.int64(4049),
 'orphan': np.int64(3205),
 'carefree': np.int64(681),
 'existence': np.int64(1541),
 'jordan': np.int64(2413),
 'college': np.int64(895),
 'otherworldly': np.int64(3210),
 'north': np.int64(3135),
 'unaware': np.int64(4668),
 'england': np.int64(1469),
 'experiment': np.int64(1555),
 'animal': np.int64(223),
 'basedonyoungadultnovel': np.int64(414),
 'nicolekidman': np.int64(3122),
 'york': np.int64(4977),
 'ambitious': np.int64(187),
 'movie': np.int64(3015),
 'producer': np.int64(3490),
 'hired': np.int64(2062),
 'crew': np.int64(1042),
 'skull': np.int64(4112),
 'island': np.int64(2288),
 'encounter': np.int64(1454),
 'kong': np.int64(2525),
 'giant': np.int64(1851),
 'ape': np.int64(255),
 'smitten': np.int64(4132),
 'lady': np.int64(2545),
 'filmmaking': np.int64(1683),
 'filmproducer': np.int64(1684),
 'dinosaur': np.int64(1249),
 'naomiwatts': np.int64(3058),
 'jackblack': np.int64(2299),
 'adrienbrody': np.int64(105),
 'rose': np.int64(3814),
 'tells': np.int64(4451),
 'story': np.int64(4279),
 'lewis': np.int64(2618),
 'bobby': np.int64(521),
 'april': np.int64(269),
 'called': np.int64(641),
 'upper': np.int64(4725),
 'class': np.int64(844),
 'passengers': np.int64(3271),
 'mother': np.int64(3002),
 'ruth': np.int64(3845),
 'fiancé': np.int64(1659),
 'drifter': np.int64(1335),
 'best': np.int64(463),
 'friend': np.int64(1780),
 'win': np.int64(4903),
 'game': np.int64(1805),
 'voyage': np.int64(4812),
 '20': np.int64(33),
 'morning': np.int64(2996),
 'panic': np.int64(3245),
 'katewinslet': np.int64(2458),
 'leonardodicaprio': np.int64(2606),
 'age': np.int64(126),
 'pass': np.int64(3268),
 'act': np.int64(77),
 'designed': np.int64(1197),
 'activity': np.int64(84),
 'causing': np.int64(723),
 'factions': np.int64(1584),
 'america': np.int64(190),
 'causes': np.int64(722),
 'allies': np.int64(170),
 'civilwar': np.int64(836),
 'scarlettjohansson': np.int64(3905),
 'radio': np.int64(3576),
 'comes': np.int64(914),
 'form': np.int64(1746),
 'waters': np.int64(4852),
 'hawaii': np.int64(1995),
 'lieutenant': np.int64(2625),
 'alex': np.int64(157),
 'hopper': np.int64(2109),
 'weapons': np.int64(4859),
 'officer': np.int64(3168),
 'assigned': np.int64(323),
 'paul': np.int64(3286),
 'hostile': np.int64(2119),
 'force': np.int64(1735),
 'unimaginable': np.int64(4695),
 'strength': np.int64(4289),
 'taking': np.int64(4405),
 'invaders': np.int64(2265),
 'live': np.int64(2650),
 'potential': np.int64(3433),
 'brother': np.int64(593),
 'fiancée': np.int64(1660),
 'shane': np.int64(4028),
 'fight': np.int64(1668),
 'navy': np.int64(3075),
 'hongkong': np.int64(2098),
 'soccer': np.int64(4139),
 'scientist': np.int64(3920),
 'peterberg': np.int64(3323),
 'park': np.int64(3256),
 'features': np.int64(1640),
 'fully': np.int64(1792),
 'dna': np.int64(1289),
 'suspense': np.int64(4389),
 'amusementpark': np.int64(200),
 'animalattack': np.int64(224),
 'animalhorror': np.int64(225),
 'assignment': np.int64(324),
 'wrong': np.int64(4967),
 'exposed': np.int64(1566),
 'attacked': np.int64(334),
 'forcing': np.int64(1738),
 'cause': np.int64(720),
 'authority': np.int64(359),
 'position': np.int64(3424),
 'challenged': np.int64(743),
 'intelligence': np.int64(2248),
 'inside': np.int64(2233),
 'ally': np.int64(173),
 'trust': np.int64(4628),
 'aided': np.int64(140),
 'field': np.int64(1664),
 'eve': np.int64(1519),
 'lethal': np.int64(2613),
 'hidden': np.int64(2038),
 'sociopath': np.int64(4143),
 'killer': np.int64(2501),
 'judidench': np.int64(2429),
 'javierbardem': np.int64(2327),
 'going': np.int64(1873),
 'major': np.int64(2743),
 'crisis': np.int64(1048),
 'burned': np.int64(623),
 'decides': np.int64(1161),
 'leaves': np.int64(2592),
 'suffering': np.int64(4333),
 'wake': np.int64(4817),
 'doc': np.int64(1290),
 'feelings': np.int64(1646),
 'mary': np.int64(2804),
 'jane': np.int64(2318),
 'girl': np.int64(1856),
 'childhood': np.int64(782),
 'doctor': np.int64(1291),
 'supervillain': np.int64(4358),
 'apart': np.int64(252),
 'starts': np.int64(4236),
 'odyssey': np.int64(3163),
 'retribution': np.int64(3715),
 'tennessee': np.int64(4453),
 'gwynethpaltrow': np.int64(1946),
 'doncheadle': np.int64(1309),
 'alice': np.int64(160),
 'individual': np.int64(2210),
 '19': np.int64(15),
 'english': np.int64(1470),
 'engagement': np.int64(1467),
 'party': np.int64(3266),
 'escapes': np.int64(1501),
 'marriage': np.int64(2783),
 'hole': np.int64(2078),
 'garden': np.int64(1813),
 'unusual': np.int64(4721),
 'rabbit': np.int64(3564),
 'arriving': np.int64(294),
 'strange': np.int64(4282),
 'surreal': np.int64(4372),
 'place': np.int64(3362),
 'nightmares': np.int64(3127),
 'child': np.int64(779),
 'filled': np.int64(1676),
 'talking': np.int64(4411),
 'animals': np.int64(226),
 'queens': np.int64(3554),
 'reason': np.int64(3618),
 'conquer': np.int64(961),
 'horrific': np.int64(2111),
 'restore': np.int64(3708),
 'throne': np.int64(4513),
 'annehathaway': np.int64(232),
 'timburton': np.int64(4524),

In [13]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
similarity = cosine_similarity(vectors)

In [16]:
similarity.shape

(4806, 4806)

In [17]:
similarity[0]

array([1.        , 0.09107651, 0.06071767, ..., 0.02519763, 0.02817181,
       0.        ], shape=(4806,))

In [30]:
def recommender(movies_list):
    new_list = [movie.lower() for movie in movies_list]
    recommendation = []
    for mov in new_list:
        index = df[df["title"].str.lower() == mov].index[0]
        distance = sorted(list(enumerate(similarity[index])),reverse=True, key=lambda x:x[1])
        for i in distance[0:4]:
            recommendation.append(df.iloc[i[0]].title)
    return recommendation

In [31]:
recommender(["Avatar", "Titanic"])

['Avatar',
 'Titan A.E.',
 'Small Soldiers',
 'Independence Day',
 'Titanic',
 'Captain Phillips',
 'The Notebook',
 'In the Heart of the Sea']

In [33]:
#export the file for the real world applications

import pickle
pickle.dump(similarity,open("similarity.pkl", "wb"))